app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



// Front Routes
Route::get('/', 'HomeController@index');

Route::post('/front-pegawai/search', [
    'as'  => 'front.pegawai.search',
    'uses'  => function() {
        $nip = Input::get('nip');

        return redirect(route('front.pegawai.show', $nip));
    }
]);

Route::get('/front-pegawai/{nip}', [
    'as'  => 'front.pegawai.show',
    'uses'  => 'HomeController@getPegawai'
]);


Route::group(['prefix' => 'cp', 'middleware' => 'auth'], function () {
	
	Route::get('dashboard', [
		'as' 	=> 	'cp.dashboard',
		'uses' 	=>	'PanelController@dashboard'
	]);

	Route::resource('pegawai', 'EmployeeController');

    Route::get('pegawai/{id}/file', [
        'as' => 'cp.pegawai.file',
        'uses' => 'EmployeeController@getFile'
        ]);

    Route::resource('instansi', 'InstituteController');

    Route::resource('jabatan', 'PositionController');

    Route::resource('callcenter', 'CallCenterController');

    Route::resource('users', 'UserController');

});

// Authentication Routes

Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::post('auth/login', 'Auth\AuthController@postLogin');

Route::get('auth/logout', 'Auth\AuthController@getLogout');

resources/views/cp/dashboard.blade.php
@extends('cp.master')

@section('content')

	<div class="row">
		<div class="col-md-12">
			<h1 class="ui header">Dashboard
			<div class="sub header">Walcome {{ Auth::user()->level }}!</div>
			</h1>
			<div class="ui divider"></div>
		</div>
	</div>

	@if(Session::has('error-user'))
		<div class="alert alert-danger">
		{{ Session::get('error-user') }}
		</div>
	@endif

	<div class="ui fluid container">
		<h3 class="ui yellow header">Broadcast Message</h3>
		<div class="ui feed">
			<div class="event">
    		<div class="content">
      		<div class="summary">
        		<a href="http://digitalcrafter.net" class="dc link">digitalcrafter</a>
        		<div class="date">
          		make dreams come true
        		</div>
      		</div>
      		<div class="extra text">
        		digitalcrafter merilis Directory App untuk kota dan kabupaten, saat ini telah hadir versi 1.3.2 dan versi development.
      		</div>
        	<div class="ui divider"></div>
    		</div>
  		</div>
			<div class="event">
    		<div class="content">
      		<div class="summary">
        		<a href="http://digitalcrafter.net" class="dc link">digitalcrafter</a>
        		<div class="date">
          		make dreams come true
        		</div>
      		</div>
      		<div class="extra text">
        		Penambahan 12 fitur di aplikasi eKTA telah di rilis bersamaan di 11 kabupaten/kota, untuk panduan silahkan ke link: <a href="http://digitalcrafter.net">digitalcrafter.net/docs</a>
      		</div>
        	<div class="ui divider"></div>
    		</div>
  		</div>
		</div>
		<h3 class="ui yellow header">Static Employee</h3>
		<div class="ui two column grid stackable">
			<div class="column">
				<h4 class="ui grey header">New Employee</h4>
				<div class="ui middle aligned animated list">
					@foreach($pegawai->take(3) as $peg)
					<div class="item">
    				<img class="ui avatar image" src="{{ asset($peg->photo1) }}">
    				<div class="content">
      				<div class="header">{{ $peg->name }}</div>
							<div class="description">{{ $peg->position->name }}</div>
    				</div>
  				</div>
					@endforeach
				</div>
			</div>
			<div class="column">
				<h4 class="ui grey header">All Data</h4>
				<div class="ui divided list">
					<div class="item">
    				<div class="ui orange horizontal circular label">{{ $pegawai->count() }}</div>
    					Employees
  				</div>
					<div class="item">
    				<div class="ui olive horizontal circular label">{{ $instansi->count() }}</div>
    					Institute
  				</div>
					<div class="item">
    				<div class="ui blue horizontal circular label">{{ $jabatan->count() }}</div>
    					Position
  				</div>
				</div>
			</div>
		</div>
		<!-- <div class="col-md-6 stats">
			<a class="ui violet image label">
  			Jumlah Pegawai
  			<div class="detail">{{ $pegawai->count() }}</div>
			</a>
			<div class="ui statistic">
  			<div class="value">
    			{{ $pegawai->count() }}
  			</div>
  			<div class="label">
    			Pegawai
  			</div>
			</div>
		</div> -->
		<!-- <div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					Pegawai Berdasarkan Instansi
				</div>
				<div class="panel-body">
					<table class="table">
						<thead>
							<tr>
								<th>Nama</th>
								<th>Jumlah</th>
							</tr>
						</thead>
						<tbody>
							@foreach($instansi as $ins)
							<tr>
								<td>{{ $ins->name }}</td>
								<td>{{ $ins->employee->count() }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div> -->
		<!-- <div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					Pegawai Berdasarkan Jabatan
				</div>
				<div class="panel-body">
					<table class="table">
						<thead>
							<tr>
								<th>Nama</th>
								<th>Jumlah</th>
							</tr>
						</thead>
						<tbody>
							@foreach( $jabatan as $jab )
							<tr>
								<td>{{ $jab->name }}</td>
								<td>{{ $jab->employee->count() }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div> -->
	</div>
@endsection

resources/views/cp/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="_csrf_token" content="{{ csrf_token() }}">

	<title>eKTA Satpol PP</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ asset('css/main.css') }}">
	<link rel="stylesheet" href="{{ asset('css/semantic.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
	<style media="screen">
		body {
			background-color: #f8fafb;
			color: #444444;
			text-shadow: 0px 1px 0px rgba(255, 255, 255, 1);
		}
		h1, h2, h3, h4, h5 {
			color: #444444;
			text-shadow: 0px 1px 0px rgba(255, 255, 255, 1);
		}
		a {
			color: #17599a;
			text-decoration: none;
		}
		a:hover {
			color: #0c74da;
		}
		.dc.containers {
			margin: 60px 0;
		}
		.dc.title {
			font-size: 43px;
		}
		.dc.main {
			border-radius: 0.9em;
			padding: 30px 25px;
			background-color: white;
			overflow: hidden;
			border: 3px solid #00B5AD!important;
		}
		.dc.mansory  {
			-webkit-column-count: 2;
			   -moz-column-count: 2;
			        column-count: 2;
			-webkit-column-gap: 0;
			   -moz-column-gap: 0;
			        column-gap: 0;
		}
		.dc.link {
			font-size: 1.14em;
		}
		.ui.text.menu {
			text-align: right;
		}
		.ui.vertical.text.menu .item {
			margin: 25px 0px;
			/*font-weight: 300;*/
		}
		.ui.vertical.text.menu .item:hover i.icon {
			color: #F2711C!important;
		}
		.ui.vertical.text.menu .item i.icon {
			margin: 0 0 0 10px;
		}
		.ui.feed > .event > .content .extra.text {
			line-height: 1.7285em;
			word-spacing: .1em;
			margin: .9em 0 0;
			font-size: 1.13em;
			padding-left: 17px;
			border-left: 3px solid rgba(0, 181, 173, 0.54);
		}
		.ui.fluid.card{
			display: inline-block;
		}
	</style>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<!-- <section id="top-navbar">
		@include('components.top-navbar')
	</section> -->

	@if(Session::has('error') || Session::has('success'))
		@include('components.alert')
	@endif

	<section id="main-content">
		<div class="ui container">
			<div class="ui container">
				<div class="dc containers">
					<div class="ui secondary labeled icon menu">
					  <div class="item">
					  	<h1 class="dc title">eKTA Satpol PP</h1>
					  </div>
						<div class="item">
							<a href="{{ route('cp.pegawai.create') }}" class="mini ui teal basic button">
								<i class="plus icon"></i>
								Quick add Employee</a>
						</div>
  					<div class="right menu">
							<div class="item">
								<h3 class="ui teal header">Hello!</h3>
							</div>
    					<div class="item">
								@if(Auth::user())
								<h3 class="ui teal header">{{ Auth::user()->name }}
									<div class="sub header">{{ Auth::user()->email }}</div>
								</h3>
								@endif
    					</div>
							<a href="{{ url('/auth/logout')}}" class="item">
									<i class="log out orange icon"></i>
  						</a>
  					</div>
					</div>
					<div class="dc containers">
						<div class="ui stackable grid">
							<div class="four wide column">
								@include('components.left-navbar')
							</div>
							<div class="twelve wide column">
								<div class="dc main">
									@yield('content')
								</div>
							</div>
						</div>
					</div>
					</div>
			</div>
		</div>
	</section>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script src="{{ asset('js/select2.min.js') }}"></script>
	<script src="{{ asset('js/jquery-2.1.4.js') }}"></script>
	<script src="{{ asset('js/semantic.min.js') }}"></script>
	<script src="{{ asset('js/sweetalert2.min.js') }}"></script>
	<script src="{{ asset('js/main.js') }}"></script>
</body>
</html>